#!/bin/bash
SC="$(dirname  "$BASH_SOURCE[0]")"

TWOPIROOT=$SC
echo $SC
source ${SC}/configure_env.sh

# define two alias as text 
# ALIAS_PISCOPE="alias piscope=\"${TwoPiRoot}/bin/piscope -e ${INTERPRETER}\""
ALIAS_PISCOPE="alias piscope=\"${TwoPiRoot}/bin/piscope -e ${PYTHON}\""
ALIAS_CIAO="alias ciao=\"echo Addio!;exit\""
ALIAS_TWOPI="alias twopi=\"${TwoPiRoot}/TwoPi/bin/twopi\""

#Prompot
# Note: Change color code based on following BASH colors
#Color	Code  Black	0;30
#              Blue	0;34
#              Green	0;32
#              Cyan	0;36
#              Red	0;31
#              Purple	0;35
#              Brown	0;33
#              Blue	0;34
#              Green	0;32
#              Cyan	0;36
#              Red	0;31
#              Purple	0;35
#              Brown	0;33
PPS1="("${TWOPIVER}")"
PPS1="\[\e[1;32m\]"${PPS1}"\[\e[0m\]"
#export PS1=${PS1}"\\h:\[\e[01;34m\]\w \[\e[0m\]\u\$ "
PPS1=${PPS1}"\\h:\[\e[01;34m\]\w \[\e[0m\]\u\$ "
PPS2="PS1=\"""${PPS1}""\""

BASH="$(command -v bash)"
echo "starting ..." ${BASH}

${BASH} --rcfile <(cat ~/.bashrc; echo "${PPS2}"; echo "${ALIAS_PISCOPE}"; echo "${ALIAS_CIAO}"; echo "${ALIAS_TWOPI}")



